# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - django-sub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://djangosub.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_78865e0c69c145bbb542bffbe91632aa }}
        password: ${{ secrets.AzureAppService_ContainerPassword_219421b8e925490e90577bfe6610ec9a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: djangosub.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_78865e0c69c145bbb542bffbe91632aa }}/prod:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'django-sub'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ba729d8b27cf47368ce71b2f64889e11 }}
        images: 'djangosub.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_78865e0c69c145bbb542bffbe91632aa }}/prod:${{ github.sha }}'